steps:
  - id: "generate random values"
    name: python
    entrypoint: python
    args: ["generate-random-numbers.py"]
  - id: "build image"
    name: docker
    entrypoint: sh
    args: ['-c',
           'docker build --build-arg=latency="$(cat /random-numbers/latency.dat)" --build-arg=randomColorFloat="$(cat /random-numbers/randomColorFloat.dat)" --build-arg=errorrate="$(cat /random-numbers/errorrate.dat)" -t testing .'
          ]
  - id: "test image"
    name: docker
    args:
    - run
    - testing
    - npm
    - run
    - test
options:
  volumes:
  - name: "random-numbers"
    path: "/random-numbers"
