kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-canary
  namespace: deployment-experiment
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: sample
        role: frontend
        env: canary
      annotations:
        prometheus.io/scrape: true
    spec:
      containers:
      - name: frontend
        image: gcr.io/lsm-data-infra/deployment-experiment
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - name: frontend
          containerPort: 8080
        env:
        - name: ENVIRONMENT_TYPE
          value: canary
