apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-prod
  name: frontend-prod
  namespace: deployment-experiment
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample
    role: frontend
  sessionAffinity: None
  type: LoadBalancer
